const assert = require("node:assert/strict")
const fs = require("node:fs")
const vm = require("node:vm")
const path = require("node:path")
const assets = vm.createContext({Qt: {locale: () => "en-US"}})
vm.runInContext(fs.readFileSync(path.join(__dirname, "../MarketAssets.js"), "utf8"), assets)
const symbols = Array.from(assets.symbols())
assert.equal(new Set(symbols).size, symbols.length)
assert.deepEqual(symbols, symbols.slice().sort())
for (const symbol of ["^SPX", "^VIX", "ES=F", "GC=F", "BTC-USD", "^TNX", "EURUSD=X"]) assert.ok(symbols.includes(symbol), symbol)
assert.equal(assets.price({format: "yield"}, 5.0664), "5.066%")
assert.equal(assets.price({format: "fx"}, 1.139731), "1.1397")
assert.equal(assets.price({}, null), "—")
assert.equal(symbols.length, 34)
const ranked = Array.from(assets.rankedSectors({XLK: {percent: -.5}, XLE: {percent: 1.5}, XLU: {percent: -1.7}, XLF: {}}), row => row.symbol)
assert.deepEqual(ranked, ["XLE", "XLK", "XLU"])
console.log("market assets ok")
