const assert = require("node:assert/strict")
const fs = require("node:fs")
const vm = require("node:vm")
const path = require("node:path")
const assets = vm.createContext({Qt: {locale: () => "en-US"}})
// Qt's JavaScript engine lacks flatMap; fail here rather than in the shell.
vm.runInContext("delete Array.prototype.flatMap; delete Array.prototype.flat", assets)
vm.runInContext(fs.readFileSync(path.join(__dirname, "../qml/market/MarketAssets.js"), "utf8"), assets)
const symbols = Array.from(assets.symbols())
assert.equal(new Set(symbols).size, symbols.length)
assert.deepEqual(symbols, symbols.slice().sort())
for (const symbol of ["^SPX", "^VIX", "ES=F", "^N225", "GC=F", "BTC-USD", "^TNX", "EURUSD=X"]) assert.ok(symbols.includes(symbol), symbol)
assert.equal(assets.price({format: "yield"}, 5.0664), "5.066%")
assert.equal(assets.price({format: "fx"}, 1.139731), "1.1397")
assert.equal(assets.price({}, null), "—")
assert.equal(symbols.length, 39)
const spx = assets.benchmarks[0], vix = assets.benchmarks[3]
assert.equal(assets.benchmark(spx, false).symbol, "^SPX")
assert.equal(assets.benchmark(spx, true).symbol, "ES=F")
assert.equal(assets.benchmark(spx, true).futures, true)
assert.equal(assets.benchmark(vix, true).symbol, "^VIX")
const ranked = Array.from(assets.rankedSectors({XLK: {percent: -.5}, XLE: {percent: 1.5}, XLU: {percent: -1.7}, XLF: {}}), row => row.symbol)
assert.deepEqual(ranked, ["XLE", "XLK", "XLU"])
console.log("market assets ok")
